FORMAT: 1A
HOST: http://private-6f6d1-dsw.apiary-mock.com

# DSW Server API Docs

## Group Info

### Info Endpoint [/info]

#### Get information about running application [GET]

+ Response 200 (application/json)

        {
            "name": "Data Stewardship Wizard Server",
            "version": "1.0.0",
            "builtAt": "2017/10/25 19:50:20Z"
        }

## Group Token

### Token Endpoint [/tokens]

#### Get token [POST]

- **Possible failures:**
  - HTTP 400
    - Invalid JSON
    - Missing required property

+ Request (application/json)
            
        {
            "email": "john.doe@example.com",
            "password": "password"
        }

+ Response 201 (application/json)

        {
            "token": "jij23ioin23.br34htjdsuis.df789323n23jn2"
        }

## Group Organization

### Organization Current [/organizations/current]

#### Get Current Organization [GET]

- **Possible failures:**
  - HTTP 401

+ Request (application/json)

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2

+ Response 200 (application/json)

    + Attributes (Organization)
        

#### Change Current Organization [PUT]

- **Possible failures:**
  - HTTP 400
    - Invalid JSON
    - Missing required property
    - GroupId is not in valid format
  - HTTP 401
  - HTTP 403
    - You don’t have ORG_PERM permission

+ Request (application/json)

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2
    
    + Attributes (Organization)
        

+ Response 200 (application/json)

    + Attributes (array[Organization])

## Group Users

### Users Collection [/users]

#### List All Users [GET]

- **Required permissions:** UM_PERM

- **Possible failures:**
  - HTTP 401
  - HTTP 403
    - You don’t have UM_PERM permission

+ Request

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2

+ Response 200 (application/json)

    + Attributes (array[User])

#### Registrate/Create user [POST]

- **Required permissions:** UM_PERM (Just for creation, not registration)

- **Possible failures:**
  - HTTP 400
    - Invalid JSON
    - Missing required property
    - User with email 'albert.einstein@example.com' already exists
  - HTTP 401 (Just for creation, not registration)
  - HTTP 403
    - You don’t have UM_PERM permission (Just for creation, not registration)

+ Request (application/json)

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2

    + Attributes (UserRegistration)
    
+ Response 201 (application/json)

    + Attributes (User)

+ Request (application/json)

    + Attributes (UserCreate)
    
+ Response 201 (application/json)

    + Attributes (User)

    
### User [/users/{userUuid}]

#### Get user [GET]

- **Required permissions:** UM_PERM

- **Possible failures:**
  - HTTP 401
  - HTTP 403
    - You don’t have UM_PERM permission
  - HTTP 404
    - User doesn't exist
    
+ Parameters
    + userUuid: 2j3hj4 (string) ... UUID of the User
    
+ Request

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2
    
+ Response 200

    + Attributes (User)

#### Modify user [PUT]

- **Required permissions:** UM_PERM

- **Possible failures:**
  - HTTP 400
    - Invalid JSON
    - Missing required property
    - User with email 'albert.einstein@example.com' already exists
  - HTTP 401
  - HTTP 403
    - You don’t have UM_PERM permission
  - HTTP 404
    - User doesn't exist
    
+ Parameters
    + userUuid: 2j3hj4 (string) ... UUID of the User
    
+ Request (application/json)

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2

    + Attributes (UserChange)    
    
+ Response 200

    + Attributes (User)

#### Activate user [PUT /users/{userUuid}/state]

- **Required permissions:** UM_PERM

- **Possible failures:**
  - HTTP 401
  - HTTP 403
    - You don’t have UM_PERM permission
  - HTTP 404
    - User doesn't exist

+ Parameters
    + userUuid: 2j3hj4 (string) ... UUID of the User
    
+ Request (application/json)

    + Attributes (UserChange)    
    
+ Response 200

    + Attributes (User)

#### Change password [PUT /users/{userUuid}/password]

- **Required permissions:** UM_PERM

- **Possible failures:**
  - HTTP 400
    - Invalid JSON
    - Missing required property
    - You have to log in as Administrator or you have to provide a hash in query param
  - HTTP 401
  - HTTP 403
    - You don’t have UM_PERM permission
  - HTTP 404
    - User doesn't exist
    
+ Parameters
    + userUuid: 2j3hj4 (string) ... UUID of the User
    
+ Request (application/json)

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2

    + Attributes (UserPasswordChange)    
    
+ Response 204

#### Reset forgotten password [PUT /users/{userUuid}/password{?hash}]

- **Possible failures:**
  - HTTP 400
    - Invalid JSON
    - Missing required property
    - You have to log in as Administrator or you have to provide a hash in query param
    - Hash query param has to be provided
  - HTTP 404
    - User doesn't exist
    
+ Parameters
    + userUuid: 2j3hj4 (string) ... UUID of the User
    + hash: h53j1jb (string) ... Random generated hash, provided in email
    
+ Request (application/json)

    + Attributes (UserPasswordChange)    
    
+ Response 204

#### Delete user [DELETE]

- **Required permissions:** UM_PERM

- **Possible failures:**
  - HTTP 401
  - HTTP 403
    - You don’t have UM_PERM permission
  - HTTP 404
    - User doesn't exist
    
+ Parameters
    + userUuid: 2j3hj4 (string) ... UUID of the User

+ Request

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2

+ Response 204

### User Current [/users/current]

#### Modify profile [PUT]

- **Possible failures:**
  - HTTP 400
    - Invalid JSON
    - Missing required property
    - User with email 'albert.einstein@example.com' already exists
  - HTTP 401
    
+ Request (application/json)

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2

    + Attributes (UserProfileChange)    
    
+ Response 200

    + Attributes (User)

#### Change password for current user [PUT /users/current/password]

- **Required permissions:** UM_PERM

- **Possible failures:**
  - HTTP 400
    - Invalid JSON
    - Missing required property
  - HTTP 401

+ Request (application/json)

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2

    + Attributes (UserPasswordChange)    
    
+ Response 204

        
## Group Questionnaires

### Questionnaires Collection [/questionnaires]

#### List All Questionnaires [GET]

- **Required permissions:** QTN_PERM

+ Response 200 (application/json)

        [
            {
                "uuid": "521ba33b-10cf-4829-bbe1-90ea06a68f4f",
                "name": "My First Wizard",
                "package": {
                    "id": "elixir.nl:core-nl:2.0.0",
                    "name": "Elixir Netherlands",
                    "groupId": "elixir.nl",
                    "artifactId": "core-nl",
                    "version": "2.0.0",
                    "description": "Updated experts",
                    "parentPackageId": "elixir:core:2.0.0"
                }
            }
        ]

#### Create a New Questionnaire [POST]

- **Required permissions:** QTN_PERM

+ Request (application/json)

        {
            "name": "My First Wizard",
            "packageId": "elixir.nl:core-nl:2.0.0"
        }

+ Response 201 (application/json)

        {
            "uuid": "521ba33b-10cf-4829-bbe1-90ea06a68f4f",
            "name": "My First Wizard",
            "package": {
                "id": "elixir.nl:core-nl:2.0.0",
                "name": "Elixir Netherlands",
                "groupId": "elixir.nl",
                "artifactId": "core-nl",
                "version": "2.0.0",
                "description": "Updated experts",
                "parentPackageId": "elixir:core:2.0.0"
            }
        }

### Questionnaire Public [/questionnaires/public]

#### Get public example ofquestionnaire [GET]

+ Response 200 (application/json)

        {
            "uuid": "0509da0e-e79f-4d56-845e-2468f8b33f09",
            "name": "Public Questionnaire",
            "package": {
                "id": "elixir.nl:core-nl:2.0.0",
                "name": "Elixir Netherlands",
                "groupId": "elixir.nl",
                "artifactId": "core-nl",
                "version": "2.0.0",
                "description": "Updated experts",
                "parentPackageId": "elixir:core:2.0.0"
            },
            "knowledgeModel": {
                "uuid": "ff672529-e837-4201-b7b1-7ada557d9725",
                "name": "My Knowledge Model",
                "chapters": [
                    {
                        "text": "Looong long text",
                        "uuid": "e3c4b314-919b-418d-bb85-a07c97433427",
                        "questions": [],
                        "title": "Design of experiment"
                    },
                    {
                        "text": "Some long text",
                        "uuid": "ca46cd40-3999-4f0d-a8ba-15d57682dfeb",
                        "questions": [],
                        "title": "Testing"
                    }
                ]
            },
            "replies": []
        }
        
        
### Questionnaire [/questionnaires/{questionnaireUuid}]

#### Get detail of Questionnaire [GET]

- **Required permissions:** QTN_PERM

+ Parameters
    + questionnaireUuid (string) ... UUID of the questionnaire

+ Response 200 (application/json)

        {
            "uuid": "521ba33b-10cf-4829-bbe1-90ea06a68f4f",
            "name": "My First Questionnaire",
            "package": {
                "id": "elixir.nl:core-nl:2.0.0",
                "name": "Elixir Netherlands",
                "groupId": "elixir.nl",
                "artifactId": "core-nl",
                "version": "2.0.0",
                "description": "Updated experts",
                "parentPackageId": "elixir:core:2.0.0"
            },
            "knowledgeModel": {
                "uuid": "ff672529-e837-4201-b7b1-7ada557d9725",
                "name": "My Knowledge Model",
                "chapters": [
                    {
                        "text": "Looong long text",
                        "uuid": "e3c4b314-919b-418d-bb85-a07c97433427",
                        "questions": [],
                        "title": "Design of experiment"
                    },
                    {
                        "text": "Some long text",
                        "uuid": "ca46cd40-3999-4f0d-a8ba-15d57682dfeb",
                        "questions": [],
                        "title": "Testing"
                    }
                ]
            },
            "replies": [
                { "path": "chapter1.question1.answer1", "value": "foo"},
                { "path": "chapter1.question1.answer2", "value": "bar"}
            ]
        }
        

#### Update replies of Questionnaire [PUT /questionnaires/{questionnaireUuid}/replies]

- **Required permissions:** QTN_PERM

+ Parameters
    + questionnaireUuid (string) ... UUID of the questionnaire
    
+ Request (application/json)

    + Attributes (QuestionnaireReply)

+ Response 200 (application/json)

    + Attributes (QuestionnaireReply)


#### Export Questionnaire [GET /questionnaires/{questionnaireUuid}/dmp{?format}]
    
+ Parameters
    + questionnaireUuid (string) ... UUID of the questionnaire
    + format: pdf (enum[string]) ... Desired document format
      + Members
            + `json`
            + `html`
            + `latex`
            + `html`
            + `docx`
            + `odt`
            + `pdf`
            + `rtf`
            + `rst`
            + `asciidoc`
            + `dokuwiki`
            + `mediawiki`
            + `epub2`
            + `epub3`

+ Response 200 (application/octet-stream)

## Group Book References

### Book Reference [/book-references/{brShortUuid}]

#### Get detail of Questionnaire [GET]

- **Possible failures:**
  - HTTP 404
  
+ Parameters
    + brShortUuid (string) ... Short uuid of book reference

+ Response 200 (application/json)

    + Attributes (BookReference)


# Data Structures

## Organization (object)

+ uuid: d0619a24db8a48e1a0330d4ef8b8da78 (string)
+ name: Elixir Amsterdam (string)
+ groupId: elixir.nl.amsterdam (string)

## User (object)

+ uuid: 3ef960678e7a479eae181be47f0e2a5d (string)
+ name: Albert (string)
+ surname: Einstein (string)
+ email: albert.einstein@example.com (string)
+ role: ADMIN (string)
+ permissions: [UM_PERM, PM_PERM] (array[string])
+ isActive: true (boolean)
+ createdAt: 2018-03-11T10:13:51+00:00 (datetime)
+ updatedAt: 2018-05-11T10:13:51+00:00 (datetime)

## UserRegistration (object)

+ name: Albert (string)
+ surname: Einstein (string)
+ email: albert.einstein@example.com (string)
+ password: aijio2jiasjdias (string)

## UserCreate (object)

+ name: Albert (string)
+ surname: Einstein (string)
+ email: albert.einstein@example.com (string)
+ role: ADMIN (string)
+ password: aijio2jiasjdias (string)

## UserChange (object)

+ uuid: 3ef960678e7a479eae181be47f0e2a5d (string)
+ name: Albert (string)
+ surname: Einstein (string)
+ email: albert.einstein@example.com (string)
+ role: ADMIN (string)
+ isActive: true (boolean)

## UserProfileChange (object)

+ uuid: 3ef960678e7a479eae181be47f0e2a5d (string)
+ name: Albert (string)
+ surname: Einstein (string)
+ email: albert.einstein@example.com (string)

## UserPasswordChange (object)

+ password: aijio2jiasjdias (string)

## QuestionnaireReply (object)

+ path: i1j3io131j23i1j.i1j3io131j23i1j.i1j3io131j23i1j.0.itemName (string)
+ value: MongoDB (string)

## BookReference (object)

+ shortUuid: bvq (string)
+ content: <div>Some HTML content</div> (string)