FORMAT: 1A
HOST: http://private-6f6d1-dsw.apiary-mock.com

# DSW Server API Docs

## Group Info

### Info Endpoint [/info]

#### Get information about running application [GET]

+ Response 200 (application/json)

        {
            "name": "Data Stewardship Wizard Server",
            "version": "1.0.0",
            "builtAt": "2017/10/25 19:50:20Z"
        }

## Group Token

### Token Endpoint [/tokens]

#### Get token [POST]

- **Possible failures:**
  - HTTP 400
    - Invalid JSON
    - Missing required property

+ Request (application/json)
            
        {
            "email": "john.doe@example.com",
            "password": "password"
        }

+ Response 201 (application/json)

        {
            "token": "jij23ioin23.br34htjdsuis.df789323n23jn2"
        }

## Group Organization

### Organization Current [/organizations/current]

#### Get Current Organization [GET]

- **Possible failures:**
  - HTTP 401

+ Request (application/json)

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2

+ Response 200 (application/json)

    + Attributes (Organization)
        

#### Change Current Organization [PUT]

- **Possible failures:**
  - HTTP 400
    - Invalid JSON
    - Missing required property
    - GroupId is not in valid format
  - HTTP 401
  - HTTP 403
    - You don’t have ORG_PERM permission

+ Request (application/json)

    + Headers
    
            x-dsp-auth-token: jij23ioin23.br34htjdsuis.df789323n23jn2
    
    + Attributes (Organization)
        

+ Response 200 (application/json)

    + Attributes (array[Organization])
        
## Group Questionnaires

### Questionnaires Collection [/questionnaires]

#### List All Questionnaires [GET]

- **Required permissions:** QTN_PERM

+ Response 200 (application/json)

        [
            {
                "uuid": "521ba33b-10cf-4829-bbe1-90ea06a68f4f",
                "name": "My First Wizard",
                "package": {
                    "id": "elixir.nl:core-nl:2.0.0",
                    "name": "Elixir Netherlands",
                    "groupId": "elixir.nl",
                    "artifactId": "core-nl",
                    "version": "2.0.0",
                    "description": "Updated experts",
                    "parentPackageId": "elixir:core:2.0.0"
                }
            }
        ]

#### Create a New Questionnaire [POST]

- **Required permissions:** QTN_PERM

+ Request (application/json)

        {
            "name": "My First Wizard",
            "packageId": "elixir.nl:core-nl:2.0.0"
        }

+ Response 201 (application/json)

        {
            "uuid": "521ba33b-10cf-4829-bbe1-90ea06a68f4f",
            "name": "My First Wizard",
            "package": {
                "id": "elixir.nl:core-nl:2.0.0",
                "name": "Elixir Netherlands",
                "groupId": "elixir.nl",
                "artifactId": "core-nl",
                "version": "2.0.0",
                "description": "Updated experts",
                "parentPackageId": "elixir:core:2.0.0"
            }
        }

### Questionnaire [/questionnaires/{questionnaireUuid}]

#### Get detail of Questionnaire [GET]

- **Required permissions:** QTN_PERM

+ Parameters
    + questionnaireUuid (string) ... UUID of the questionnaire

+ Response 200 (application/json)

        {
            "uuid": "521ba33b-10cf-4829-bbe1-90ea06a68f4f",
            "name": "My First Wizard",
            "package": {
                "id": "elixir.nl:core-nl:2.0.0",
                "name": "Elixir Netherlands",
                "groupId": "elixir.nl",
                "artifactId": "core-nl",
                "version": "2.0.0",
                "description": "Updated experts",
                "parentPackageId": "elixir:core:2.0.0"
            },
            "knowledgeModel": {
                "uuid": "ff672529-e837-4201-b7b1-7ada557d9725",
                "name": "My Knowledge Model",
                "chapters": [
                    {
                        "text": "Looong long text",
                        "uuid": "e3c4b314-919b-418d-bb85-a07c97433427",
                        "questions": [],
                        "title": "Design of experiment"
                    },
                    {
                        "text": "Some long text",
                        "uuid": "ca46cd40-3999-4f0d-a8ba-15d57682dfeb",
                        "questions": [],
                        "title": "Testing"
                    }
                ]
            },
            "replies": {
                "chapter1.question1.answer1": "foo" ,
                "chapter1.question1.answer2": "bar" 
            }
        }
        
        
#### Update replies of Questionnaire [PUT /questionnaires/{questionnaireUuid}/replies]

- **Required permissions:** QTN_PERM

+ Parameters
    + questionnaireUuid (string) ... UUID of the questionnaire
    
+ Request (application/json)

        {
            "chapter1.question1.answer1": "foo",
            "chapter1.question1.answer2": "bar"
        }

+ Response 200 (application/json)

        {
            "chapter1.question1.answer1": "foo",
            "chapter1.question1.answer2": "bar"
        }
        
#### Delete detail of Questionnaire [DELETE]

- **Required permissions:** QTN_PERM

+ Parameters
    + questionnaireUuid (string) ... UUID of the questionnaire
    
+ Response 204



# Data Structures

## Organization (object)

+ uuid: d0619a24db8a48e1a0330d4ef8b8da78 (string)
+ name: Elixir Amsterdam (string)
+ groupId: elixir.nl.amsterdam (string)